server:
  ## 开启优雅停机, 如果不配置是默认IMMEDIATE, 立即停机
  shutdown: graceful
  port: 8077

spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    time-zone: GMT+8
  lifecycle:
    ## 优雅停机宽限期时间 default 30s
    timeout-per-shutdown-phase: 20s
  application:
    name: school
  thymeleaf:
    cache: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    database: mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://10.227.79.136:3306/school_demo?zeroDateTimeBehavior=CONVERT_TO_NULL&&&useAffectedRows=true
    url: jdbc:mysql://127.0.0.1:3306/school_demo?zeroDateTimeBehavior=CONVERT_TO_NULL&&&useAffectedRows=true&serverTimezone=GMT%2B8
    username: root
#    password: password
    password: 190627

  redis:
#    host: 10.227.79.136
    host: 127.0.0.1
    port: 6379
    lettuce:
      shutdown-timeout: 100ms

  profiles:
    active: default


logging:
  level:
    root: info
    web: debug



